# .goreleaser.yml
#dist: target

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download

archives:
  # Builds reference which build instances should be archived in this archive.
  - id: default
    builds:
    - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary

    # Additional files/template/globs you want to add to the archive.
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    #files:
    #  - LICENSE.txt
    #  - README_{{.Os}}.md
    #  - CHANGELOG.md
    #  - docs/*
    #  - design/*.png
    #  - templates/**/*
    files:
      - none*

builds:
  - id: default
    main: ./cmd/socketace/main.go
    binary: socketace

    # Custom flags templates.
    # Default is empty.
    # flags: []

    # Custom asmflags templates.
    # Default is empty.
    # asmflags: []

    # Custom gcflags templates.
    # Default is empty.
    # gcflags: []

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -extldflags '-static'
      - "-X github.com/bokysan/socketace/v2/internal/version.version={{ .Version }}"
      - "-X github.com/bokysan/socketace/v2/internal/version.GitCommit={{ .ShortCommit }}"
      - "-X github.com/bokysan/socketace/v2/internal/version.GitBranch={{ .Env.GIT_BRANCH }}"
      - "-X github.com/bokysan/socketace/v2/internal/version.GitTag={{ .Tag }}"
      - "-X github.com/bokysan/socketace/v2/internal/version.GitSummary="
      - "-X github.com/bokysan/socketace/v2/internal/version.BuildDate={{ .Date }}"
      # There's an issue with ldflags when the there are spaces in argument value -- this does not
      # get escaped properly lading to a weird error of how `link` cannot be called. Until the
      # issue is resolved, we will not be including the go version in the build.
      #- "-X github.com/bokysan/socketace/v2/internal/version.GoVersion='{{ .Env.GOVERSION }}'"

    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Note: building for android (at least arm64) fails:
    # https://github.com/bokysan/socketace/runs/1192744354?check_suite_focus=true#step:4:88
    # link: running gcc failed: exit status 1
    # /usr/bin/ld: /tmp/go-link-964528223/go.o: Relocations in generic ELF (EM: 183)
    #
    goos: [ 'darwin', 'linux', 'freebsd', 'netbsd', 'dragonfly', 'openbsd', 'windows' ]
    goarch: [ '386', 'amd64', 'mips', 'mips64', 'mips64le', 'mipsle', 'ppc64le', 'arm', 'arm64' ]
    goarm: [ '5', '6', '7' ]

    # There seems to be a weird issue with mipsle build, because goreleaser creates a file
    # 'socketace_1.0.2_linux_mipsle' without '_hardfloat' or '_softloat' extension. See:
    # https://github.com/bokysan/socketace/runs/1201307874?check_suite_focus=true#step:4:247
    #
    # The issue could be a bug or a configuration issue. Until we resolve this, we will build
    # softfloat only, as it's more compatible and the code doesn't use any floats either way.
    # gomips: [ 'hardfloat', 'softfloat' ]
    gomips: [ 'softfloat' ]

    ignore:
      - goos: openbsd
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: solaris
        goarch: arm

    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    #ignore:
    #  - goos: darwin
    #    goarch: 386
    #  - goos: linux
    #    goarch: arm
    #    goarm: 7
    #  - goarm: mips64
    #    gomips: hardfloat

    # Set a specific go binary to use when building. It is safe to ignore
    # this option in most cases.
    # Default is "go"
    # gobinary: "go1.13.4"

    # Set the modified timestamp on the output binary, typically
    # you would do this to ensure a build was reproducible. Pass
    # empty string to skip modifying the output.
    # Default is empty string.
    mod_timestamp: '{{ .CommitTimestamp }}'

    # Hooks can be used to customize the final binary,
    # for example, to run generators.
    # Those fields allow templates.
    # Default is both hooks empty.
    #hooks:
    #  pre: rice embed-go
    #  post: ./script.sh {{ .Path }}

    # If true, skip the build.
    # Useful for library projects.
    # Default is false
    skip: false

nfpms:
  - id: "default"
    builds: [ "default" ]
    vendor: Bokysan
    homepage: https://github.com/bokysan/socketace
    license: GNU GPL v3.0
    maintainer: Boky <https://github.com/bokysan/socketace>
    description: Your ultimate connection proxy.
    bindir: "/usr/local/bin"
    formats: [ 'apk', 'deb', 'rpm' ]
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
